# Generated by Django 4.0.5 on 2022-06-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_studentgroup_event_event_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='student',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='events',
            field=models.ManyToManyField(null=True, to='event.event'),
        ),
    ]
