# Generated by Django 4.0.5 on 2022-06-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_studentgroup_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='event.studentgroup'),
        ),
    ]
