# Generated by Django 4.0.5 on 2022-06-30 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_studentgroup_events_event_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.studentgroup'),
        ),
    ]
