# Generated by Django 4.0.5 on 2022-07-02 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentgroup_student_group'),
        ('event', '0011_alter_event_students_delete_studentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='join_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentgroup'),
        ),
    ]
